name: flutter_multitype
description: :fire::fire::fire:Easier and more flexible to create multiple types for Flutter ListView.
version: 1.0.0
homepage: https://github.com/Wenlong-Guo/flutter_multitype

environment:
  sdk: ">=2.17.1 <3.0.0"

dev_dependencies:
  test: