name: flutter_multitype
description: :fire::fire::fire:Easier and more flexible to create multiple types for Flutter ListView.
version: 0.9.2
homepage: https://github.com/Wenlong-Guo/flutter_multitype

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  test: